backend:
  name: github
  repo: lydonmn/EntropyFinancial
  branch: main
  app_id: 28333203
  client_id: iv23li73iTYZf10BQTuB
  client_secret: 585eddff196c52d662e3c85fb93865af00fa8a4d
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    SHA256:TYdOSpCunsRTKa647vyudxj2Q2WZZmuD3mUnnSUGxFo=
    -----END RSA PRIVATE KEY-----
  auth_type: pkce
  squash_merges: true

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero Title", name: "hero_title", widget: "string"}
      - {label: "Hero Tagline", name: "hero_tagline", widget: "text"}
      - {label: "Body Content", name: "body", widget: "markdown"}
  - name: "services"
    label: "Services"
    folder: "services"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
